import { ArrowUpRight, Camera, BriefcaseBusiness, Mail } from 'lucide-react'
import { Link } from 'react-router-dom'
import { contactInfo } from '../data/contactInfo'
import logo from '../assets/logo/purple-cow-logo-transparent.png'
const navLinks = [
  { label: 'Home', to: '/' },
  { label: 'About Us', to: '/about' },
  { label: 'Work', to: '/work' },
  { label: 'Contact', to: '/contact' }
]
export default function Footer(){const year=new Date().getFullYear();return <footer className="site-footer"><div className="footer-torn" aria-hidden="true"/><div className="footer-inner"><div className="footer-top"><a className="footer-brand" href="#top" aria-label="Purple Cow home"><img src={logo} alt="We Are Purple Cow"/></a><p className="footer-kicker">Got a bold idea?</p><h2>Let&apos;s make it<br/><span>impossible to ignore.</span></h2><a className="footer-cta" href="mailto:contactus@wearepurplecow.com"><span>Start a conversation</span><i><ArrowUpRight size={25}/></i></a></div><div className="footer-rule"/><div className="footer-grid"><div><p className="footer-label">Find your way</p><nav className="footer-nav" aria-label="Footer navigation">{navLinks.map(link=><Link to={link.to} key={link.label}>{link.label}</Link>)}</nav></div><div><p className="footer-label">Say hello</p><a className="footer-email" href={`mailto:${contactInfo.email}`} style={{display: 'block', width: 'max-content'}}>{contactInfo.email}</a><a className="footer-email" href={`tel:${contactInfo.phone.replace(/\s/g,'')}`} style={{display: 'block', width: 'max-content', marginTop: '10px', fontSize: '20px'}}>{contactInfo.phone}</a><p className="footer-location" style={{marginTop: '20px'}}>{contactInfo.addressLines[0]}<br/>{contactInfo.addressLines[1]}, {contactInfo.addressLines[2]}</p></div><div><p className="footer-label">Follow the noise</p><div className="footer-socials"><a href={contactInfo.socials?.instagram || '#instagram'} target="_blank" rel="noopener noreferrer" aria-label="Instagram"><Camera/></a><a href="#linkedin" aria-label="LinkedIn"><BriefcaseBusiness/></a><a href={`mailto:${contactInfo.email}`} aria-label="Email"><Mail/></a></div><a className="back-to-top" href="#top" onClick={(e) => { e.preventDefault(); window.scrollTo({top: 0, behavior: 'smooth'}); }}>Back to top <span>&uarr;</span></a></div></div><div className="footer-bottom"><p>&copy; {year} We Are Purple Cow. All rights reserved.</p><p>We don&apos;t do ordinary.</p><div><a href="#privacy">Privacy</a><a href="#terms">Terms</a></div></div></div><div className="footer-marquee" aria-hidden="true"><span>Think bold &bull; Make noise &bull; Create impact &bull; Stay purple &bull;&nbsp;</span><span>Think bold &bull; Make noise &bull; Create impact &bull; Stay purple &bull;&nbsp;</span></div></footer>}